

project_list : ['WDS','BDS','TMF']

time_start : '2019-02-20'
time_end : '2019-03-20'

URL:  'https://adlm.nielsen.com/bitbucket/rest/api/1.0'
ACCESS_TOKEN : 'Bearer OTk2NTk1MTA0MDczOhxMKpn4xWkRS8ixN51Ve+4gSxxe'


#WDS，BDS，TMF
#
